#!/bin/bash

###############################################################################
#
#   An utility script to checking which Java version compiled each submodule
#   of this project.
#
###############################################################################

echo "===================================================="
echo "Verifying Java version for classes within JAR files."
echo ""
echo "  problem4j-gson must be 52 (Java 8)"
echo ""
echo "Note that JAR files must exist (./gradlew build)."
echo ""

echo "===== problem4j-gson ===="
javap \
    -verbose \
    -classpath build/libs/problem4j-gson-*-SNAPSHOT.jar \
    io.github.problem4j.gson.ProblemTypeAdapterFactory \
    | grep "major version"
